config/routes.rb
Rails.application.routes.draw do
  get 'relationships/destroy'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :joined_groups
    end
  end
  resources :users do
    member do
      post :apply_for_join
    end
  end
  resources :mmpnotes do
    member do
      post :create_for_group
    end
  end
  resources :users
  resources :mmpnotes, only: [:create, :destroy, :show, :edit, :update]
  resources :groups
  resources :relationships, only: [:create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :relationships, foreign_key: "group_id", dependent: :destroy
  has_many :users, through: :relationships
  has_many :mmpnotes

  def add_member(other_user)
    users << other_user 
  end
  
  def delete_member(other_user)
    users.delete(other_user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @groups = Group.paginate(page: params[:page])
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    
    if current_user.groups.create(group_params)
      flash[:success] = "Success Create Group"
      redirect_to joined_groups_user_path(current_user.id)
    else
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "Group updated"
      redirect_to @group
    else
      render 'edit'
    end
  end
  
  def destroy
    
    @group = Group.find(params[:id])
    if(@group.users.empty?)
      if @group.destroy
        flash[:success] = "deleted group"
      end
    else
      flash[:failure] = "deleted group"
      redirect_to joined_groups_user_path
    end
  end

  
  def members(group)
    @title = "Members"
    @members = group.users
    render 'members'
  end
  
  private

  def group_params
    params.require(:group).permit(:name)
  end

  def correct_user
    redirect_to(root_url) unless current_user.groups.find(params[:id])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<% provide(:title, "Edit Group") %>
<h1>Update Group profile</h1>
<div>
  <div>
    <%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'All group') %>
<h1>All groups</h1>

<%= will_paginate %>
<ul class="users">
    <li>Name|ID|Users</li>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group %>|<%= group.id %>|<%= group.users.count %>
      <% if group.users.include?(current_user) %>
      <% else %>
      | <%= link_to "Join", apply_for_join_user_path(:id=>group.id), method: :post %></li>
    <% end %>
    <% if current_user.admin? %>
    <li><%= link_to "delete", group, method: :delete,
	  data: { confirm: "You sure?" } %></li>
    <% end %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/groups/new.html.erb
<% provide(:title, "New group") %>

<h1>New Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.submit "Create Group", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, "joined_group") %>
<div>
  <div>
  <%= @group.name %>
  </div>
  <div>
    <h3>Users: <%= @group.users.count %></h3>
    <ul>
      <% @group.users.each do |user| %>
      <li>
	<div class="container">
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	</div>
	<br>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="container">
    <h3>Group Notes: <%= @group.mmpnotes.count %></h3>
    <ul>
      <% @group.mmpnotes.each do |note| %>
      <li>
	<div class="container">
	  <%= link_to note.subject, note %>
	</div>
	<br>
      </li>
      <% end %>
    </ul>
  </div>
  
  <div class="btn">
    <%= link_to "Create New Group Note", new_mmpnote_path(:group_id=>@group.id) %>
  </div>
  
</div>