config/routes.rb
Rails.application.routes.draw do
  get 'relationships/destroy'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :joined_groups
    end
  end
  resources :users do
    member do
      post :apply_for_join
    end
  end
  resources :mmpnotes do
    member do
      post :create_for_group
    end
  end
  resources :users
  resources :mmpnotes, only: [:create, :destroy, :show, :edit, :update]
  resources :groups
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
#1 coding: utf-8
class User < ApplicationRecord
  has_many :mmpnotes, dependent: :destroy
  has_many :relationships, foreign_key: "user_id", dependent: :destroy
  has_many :groups, through: :relationships
  before_save{ self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #返回指定字符串的哈希摘要
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
             BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def join_group(other_group)
    groups << other_group
  end

  def exit_group(other_group)
    groups.delete(other_group)
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:eidt, :update]
  before_action :admin_user,     only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @mmpnotes = @user.mmpnotes.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
                                       
    if @user.save
      log_in @user
      flash[:success] = "Welcome to MMP NOTE!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]  = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def joined_groups
    @user = User.find(params[:id])
    @title = "Groups"
    @joined_groups = current_user.groups.all
    render 'joined_groups'
  end

  def apply_for_join
    @group = Group.find(params[:id])
    if(current_user.join_group(@group))
      flash[:success] = "success join group"
      redirect_to groups_path
    end
  end
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div>
  <div>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? %>
    | <%= link_to "delete", user, method: :delete,
	  data: { confirm: "You sure?" } %>
    <% end %>
  </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/joined_groups.html.erb
<div>
  
  <div>
    <% if @joined_groups.any? %>
    <h3>Groups (<%= @joined_groups.count %>)</h3>
    <ul>
      <% @joined_groups.each do |joined_group| %>
      <li>
	<%= link_to joined_group.name, joined_group %>|
	<%= joined_group.users.count %> | 
	<%= link_to "Exit", relationship_path(current_user.relationships.find_by(group_id: joined_group.id)), method: :delete %>
      </li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <li><%= link_to "Create New Group", new_group_path %></li>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <div>
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </div>
  
  <div>
    <% if @user.mmpnotes.any? %>
    <h3>Mmpnotes (<%= @user.mmpnotes.count %>)</h3>
    <ol>
      <%= render @mmpnotes %>
    </ol>
    <%= will_paginate @mmpnotes %>
    <% end %>
  </div>
</div>