config/routes.rb
Rails.application.routes.draw do
  get 'relationships/destroy'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :joined_groups
    end
  end
  resources :users do
    member do
      post :apply_for_join
    end
  end
  resources :mmpnotes do
    member do
      post :create_for_group
    end
  end
  resources :users
  resources :mmpnotes, only: [:create, :destroy, :show, :edit, :update]
  resources :groups
  resources :relationships, only: [:create, :destroy]
end

app/models/mmpnote.rb
class Mmpnote < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 4000}
  validates :subject, length: { maximum: 50 }
end

app/controllers/mmpnotes_controller.rb
class MmpnotesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show, :edit, :update]
  before_action :correct_user, only: [:destroy, :edit, :update] 

  def new
    @mmpnote = Mmpnote.new
    @group = Group.find(params[:group_id])
  end
  
  def create
    if(params[:group_id])
      @group = Group.find(params[:group_id])
      @mmpnote = @group.mmpnotes.build(mmpnote_params)
      if @mmpnote.save
        flash[:success] = "Group Mmpnote Created!"
        redirect_to @group
      else
        flash[:failure] = "Fail to save"
        redirect_to 'static_pages/home'
      end
    else
    @mmpnote = current_user.mmpnotes.build(mmpnote_params)
    if @mmpnote.save
      flash[:success] = "Mmpnote created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
    end
  end

  def edit
    @mmpnote = Mmpnote.find(params[:id])
  end

  def update
    @mmpnote = Mmpnote.find(params[:id])
    if @mmpnote.update_attributes(mmpnote_params)
      flash[:success] = "Note updated"
      redirect_to @mmpnote
    else
      render 'edit'
    end
  end
  
  def show
    @mmpnote = Mmpnote.find(params[:id])
  end

  def destroy
    Mmpnote.find(params[:id]).destroy
    flash[:success] = "note deleted"
    redirect_to current_user
  end

  private

  def mmpnote_params
    params.require(:mmpnote).permit(:content, :subject)
  end
  
  def correct_user
    @mmpnote = current_user.mmpnotes.find_by(id: params[:id])
    redirect_to root_url if @mmpnote.nil?
  end
end

app/helpers/mmpnotes_helper.rb
module MmpnotesHelper
end

app/views/mmpnotes/_mmpnote.html.erb
<li id="mmpnote-<%= mmpnote.id %>">
  <%= link_to gravatar_for(mmpnote.user, size: 50), mmpnote.user %>
<div class="container">
<div>
  <span>user:<%= link_to mmpnote.user.name, mmpnote.user %></span>
<br></br>
</div>
<div>
  <span>subject:<%= mmpnote.subject %></span>
<br></br>
</div>
<div>
  <%= link_to 'details', mmpnote_path(mmpnote) %> |
  <%= link_to 'delete', mmpnote, method: :delete %>
  <br></br>
  <hr>
</div>
  <span>
    Posted <%= time_ago_in_words(mmpnote.created_at) %> ago.
  </span>
</div>
</li>

app/views/mmpnotes/edit.html.erb
<%= form_for(@mmpnote) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div>
  <%= f.text_area :subject, placeholder: "Note Subject..." %>
  <%= f.text_area :content, placeholder: "Update mmpnote..." %>
</div>
<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/mmpnotes/new.html.erb
<% provide(:title, "New Group Note") %>

<section>
  <%= form_for(@mmpnote) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <%= f.text_area :subject, placeholder: "Note Subject" %>
    <%= f.text_area :content, placeholder: "Compose New mmpnote..." %>
    <%= hidden_field_tag "group_id", @group.id %>
  </div>
  <%= f.submit "Post", class: "btn-primary" %>
  <% end %>
</section>

app/views/mmpnotes/show.html.erb
<% provide(:title, @mmpnote.subject) %>
<div>
  <div>
    <h1>
      <%= @mmpnote.subject %>
    </h1>
  </div>
  <div>
    <%= @mmpnote.content %>
  </div>
  <div>
    <%= link_to "edit", edit_mmpnote_path(@mmpnote) %>
  </div>
</div>