config/routes.rb
Rails.application.routes.draw do
  get 'relationships/destroy'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :joined_groups
    end
  end
  resources :users do
    member do
      post :apply_for_join
    end
  end
  resources :mmpnotes do
    member do
      post :create_for_group
    end
  end
  resources :users
  resources :mmpnotes, only: [:create, :destroy, :show, :edit, :update]
  resources :groups
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
	<li><%= link_to "Home",   root_path %></li>
	<li><%= link_to "Help",   help_path %></li>
	<li><%= link_to "About",  about_path %></li>
	<% if logged_in? %>
	<li><%= link_to "Users", users_path %></li>
	<li><%= link_to "Groups", groups_path %></li>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	    Account<b class="caret"></b>
	  </a>
	  <ul class="dropdown-menu">
	    <li><%= link_to "My Notes", current_user %></li>
	    <li><%= link_to "My Groups", joined_groups_user_path(current_user) %></li>
	    <li><%= link_to "My Profile", edit_user_path(current_user) %></li>
	    <li class="divider"></li>
	    <li>
	      <%= link_to "Log out", logout_path, method: :delete %>
	    </li>
	  </ul>
	</li>
	<% else %>
	<li><%= link_to "Log in", login_path %></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | mmp Note </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
      <div> <%= message_type %> <%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>